### ISSUE TITLE
Some questions about Particle Lances and Tachyon Lances

### ISSUE THREAD

**Issue by cloudkylin** [turanar/stellaris-tech-tree#1]
Thank you for sharing. Is Particle Lances and Tachyon Lances wrong?

**Comment by turanar** [comment]
Tachyon Lances needs both Particle Lances and Gamma Lasers - And because i'm not currating the result manually - it attachs to Gamma Laser. 

But if you click Tachyon Lance you will see the Required Technologies includes Particles Lances.

**Comment by cloudkylin** [comment]
Ok, thank you for your answer.
