### ISSUE TITLE
Put tree nodes in columns according to tier

### ISSUE THREAD

**Issue by toolforger** [turanar/stellaris-tech-tree#12]
Knowing the tree is nice, but as a player you learn that pretty quickly.
Tier dependencies are harder to find out, and you don't know whether you should just research some cheap tier-1 tech to get the next roll faster, or that tier-2 one because you're just one tech short because you can even hope to see tier-3.

**Comment by Muhrks** [comment]
This.
It is kinda hard to read, if you have Tier 1-5 all in one column. For example, you have in society in the third column a Tier 1 tech, followed by Tier 2,3,5,4,3,3,.... Would make more sense, if same Tiers are below each other. Please change this, if possible. =)
