### ISSUE TITLE
What is required for updating to 2.8.1?

### ISSUE THREAD

**Issue by mathguthrie** [turanar/stellaris-tech-tree#13]
If I wanted to update this to 2.8.1, what would I need to do?

Thanks.

**Comment by eva-cosma** [comment]
You'll need to edit the JSON files that contain the info about the tech and how they are linked. Unfortunately, I didn't create these, but I imagine that it was done based on a combination of both looking through the game files and, at the same time, editing previous versions.
[Here is a version of the game](https://github.com/turanar/stellaris-tech-tree/tree/master/verne-2.6.0)
[And here is all the engineering tech for it](https://github.com/turanar/stellaris-tech-tree/blob/master/verne-2.6.0/engineering.json)

The current game version is ["vanilla"](https://github.com/turanar/stellaris-tech-tree/tree/master/vanilla)
