### ISSUE TITLE
[Feature Request] Deep search for tech names and research effects

### ISSUE THREAD

**Issue by rohantejeswar** [turanar/stellaris-tech-tree#16]
A feature which will let us search for not only the tech names but also the effects they unlock would be incredibly useful. For the most part the browser's search works but for that you need to know the names of the tech when all you might know is the effect you want. 

For example for something straight forward like Droids its quite easy to find. But if you want Habitability Modification, it could start to get a bit tricky. A feature which can search not just the names of the tech but also its research effects, considering all of the information is already available, might be incredibly useful for the community at large.

**Comment by BlindChickens** [comment]
Hi @rohantejeswar
This has been implemented in https://github.com/turanar/stellaris-tech-tree/pull/21, and is now live.
