### ISSUE TITLE
Offer help

### ISSUE THREAD

**Issue by BlindChickens** [turanar/stellaris-tech-tree#18]
Hi all.

If anyone that can authorise PR's on this repo can give me an indication of how I can contribute, there is nothing I can see relating to plans for the repo/site.

I have ideas and want to start implementing, but only if I can get it into the code.

Please let me know.

**Comment by turanar** [comment]
I can't believe there is not chat feature on Github. 
I would like to give you my email adress but not on a public Issue.

Can you contact me on Reddit ? 
https://www.reddit.com/user/turanar
So i can PM you my email adress ?

( Yeah a bit stupid to have to do it this way )
