### ISSUE TITLE
404 Treant.min.js

### ISSUE THREAD

**Issue by david2tm** [turanar/stellaris-tech-tree#2]
https://cdnjs.cloudflare.com/ajax/libs/treant-js/1.0/Treant.min.js is gone for some reason.

**Comment by turanar** [comment]
Looks like it's back. I wanted to use a CDN to increase speed, but i guess i will have to move all the JS / CSS to the project to be sure it doesn't disapear again.

**Comment by turanar** [comment]
Fixed - all JS and CSS are now part of the site, and not pulled from cdnjs - This should secure the availability
