### ISSUE TITLE
Re-adding the Check Box by the tech.

### ISSUE THREAD

**Issue by ScionSpy** [turanar/stellaris-tech-tree#24]
Heyo, I tend to use this as I play the game in order to keep track of which techs I've gotten and those I haven't yet.

A few updates ago you removed the options to be able to 'save' a tree by name (Useful for multiple games) and the ability to 'track' the techs with the check box.

Was wondering what the reason for the removal was, and if there was any way to re-add these features?

Thanks!

**Comment by turanar** [comment]
Hi,

I never liked this functionality, but it looks like some people did.
Did you use the save/load function too ?

I guess i can re-enable that if you find it useful.

Turanar

**Comment by ScionSpy** [comment]
Yeah, both my girl and I used the save function.
  We play multiple games at the same time, and it was useful to easily swap between the empire you were playing.

I'm not sure about others or if you have analytics, but at least 2 of us used it :P

**Comment by turanar** [comment]
Ok - I will update the app to put that back then.

Will try to do that as soon as possible.

**Comment by turanar** [comment]
Done - But it might not work if you load a tree that was saved for another version.
But should be OK if you stick only to the current version.
