### ISSUE TITLE
[BUG] The header does not scale up as it should on mobile (android)

### ISSUE THREAD

**Issue by eva-cosma** [turanar/stellaris-tech-tree#4]
Tested both on Android 4.1/API 16 and some other newer one -- forgot which -- but both have a common issue: The "resize" event does not fire when zooming.

I tried using touchy.js in another repo to try to solve the issue but the pitch detection did not work well and thought that detecting drag would be too laggy and resource intensive.

But that didn't matter because after I tried out hammer.js (which stopped the pitch to function altogether) I noticed that the document size was the exact same! Outrageous! I tried to find some other scripts that would find the scale of the window but came out empty handed as all did not function in Android.

This isn't an important issue for most but I know some would prefer to not use their browser at all to squeeze out those last bits of FPS. A workaround would be to use the in-game browser but I can not myself use it for some reason so maybe some also can not. One final workaround would be to implement the tree inside the game but that would be the definition of agony.

If anyone has any idea on how the issue can be resolved, please, do not hesitate to answer!

**Comment by turanar** [comment]
![screenshot_20190106-174242](https://user-images.githubusercontent.com/2619377/50739056-bcd30700-11da-11e9-91d0-5b8a889ae5b4.png)

**Comment by turanar** [comment]
I did change the topbar width to be 100% with CSS, and disabled the resize through Javascript.

Zooming still get the topbar out of view, I can't really do anything to improve that unfortunately. 
Fixed topbar are always been a pain to get right on mobile devices ...

**Comment by eva-cosma** [comment]
**AFTER 3 days of thinking and experimenting:**

The out-of-view issue can be solved by putting the page content in an iframe, which is a tedious and not worthwhile task, not to mention the code will be unmaintainable. Other then that touchy.js is outdated, hammer.js is **annoying** to work with and,  finally, the iframe solution will also not work because when the user scrolls up there is a high chance he will refresh the page.

**Solution:** `width:100%;` and forget about it.

**Comment by turanar** [comment]
Yeah I did try the iframe even the good old frameset / frame setup (that is deprecated in html5).
It fix the issue, but split the html in 3 files, and as i said - deprecated in html5.

So yeah - not worth the hassle.
